### ISSUE TITLE
No entry in view menu for “date range dialog for edited”

### ISSUE THREAD

**Issue by Fred-Vatin** [ijgnd/anki__BetterSearch#19]
Add-on version | Anki | OS 
------------------ | ---- | ---
2020-10-25 | ⁨2.1.37 | Win 10 x64 pro (french)1909

Everything is in the title. I can access “date range dialog for edited” using `dedited:` though. But no entry in the view menu among the other two _show date range dialog_.

**Comment by ijgnd** [comment]
thanks for reporting this. "edited:" is only supported since Anki 2.1.28 from July and when I added support for edited with "dedited:" and in the extra dialog I forgot about the view menu entries.

Your report led me to fix another bug that when you directly used these date dialogs I forgot to clear the default information text from the search bar.

I'll upload the fixed version soon.

&nbsp;

Your bug reports from today were very useful. If you find more problems or bad documentation please let me know.
