### ISSUE TITLE
Black background on window won't convert to white

### ISSUE THREAD

**Issue by starwarsstan** [ijgnd/anki__BetterSearch#2]
![image](https://user-images.githubusercontent.com/58764956/72574629-85cc1280-387e-11ea-90e1-fe54aa36e07c.png)

I can't seem to get this background to change to white. The only way it does become white is if I toggle night mode with CMD+N.

I've tried to choose what to style on nightmode and that does not resolve the issue even when unchecking everything. I also tried converting this code from "False" to "True"

night_mode_on = False
def refresh_night_mode_state(nm_state):
    global night_mode_on
    night_mode_on = nm_state
addHook("night_mode_state_changed", refresh_night_mode_state)

I am on:

- Anki 2.1.19
- Mac OS Catalina 10.15.2

**Comment by ijgnd** [comment]
Thanks for the report and helping to improve this add-on.

I assume you use the latest version of my add-on from ankiweb from 2020-01-13. just to be safe: in the add-on manager window click the button "Check for Updates".

> I've tried to choose what to style on nightmode and that does not resolve the issue even when unchecking everything.

This can't work since this only affects built-in elements from Anki. A radical solution is to disable Night mode in all dialogs by removing the check from main window -> View -> Night Mode -> Enable in dialogs. 

&nbsp;

I can only get a similar result to what you have in the following case:

- enable night mode
- open a browser window
- disable night mode. The open browser window remains styled in the night mode.
- open my quick insertion dialog. 

I don't have this problem if I close all browser windows after disabling the night mode. When I open a new browser after this and then open my  quick insertion dialog it's styled properly.

Do you also have this problem in other situations? If so, what are the exact steps to reproduce this? Please test with only night-mode and my add-on. I can only try to solve this problem if I can reproduce it on my computer and for this I need a step-by-step guide. A screencast might avoid confusion.

**Comment by ijgnd** [comment]
can you at least test my latest release on ankiweb from today and let me know if this solves your problem.

Make sure to update all your add-ons since night mode has also been updated since you created this issue.

**Comment by starwarsstan** [comment]
It improves the experience because it makes the text white on black but I cannot get the background to change to white without toggling off nightmode. 
![image](https://user-images.githubusercontent.com/58764956/73204775-6e99ea00-40f4-11ea-83ef-60a917d4fe93.png)

**Comment by ijgnd** [comment]
For me the screenshot you show is enough - the add-on is useable. I can only reproduce this if I disable the styling of some dialogs in night mode. the add-on night mode doesn't seem to tell other add-ons what's styled so fixing this doesn't seem trivial. So I won't fix this but if someone has a patch ...

Apart from this it will be a moot point soon because the upcoming Anki 2.1.20 includes a much improved night mode and the night mode developer recently wrote "Please note: the Anki 2.1.20 will ship with built-in night mode and this add-on (after 5 years of service) will become deprecated." ([source](https://www.reddit.com/r/Anki/comments/etr8fq/bugfix_release_of_the_night_mode_232_sidebar_and/))

If you have a problem with the new night mode in 2.1.20 let me know.

**Comment by starwarsstan** [comment]
That makes sense. Thanks for commenting on this.
