### ISSUE TITLE
Feature request: fuzzy search

### ISSUE THREAD

**Issue by dryBoneMarrow** [ijgnd/anki__BetterSearch#39]
It would be neat if there was a fuzzy search when searching for decks/cards/tags/... . It would be a lot faster.

**Comment by ijgnd** [comment]
Could you provide more details? 

At the moment the addon should behave simlilar to fzf (marketed as a "fuzzy finder") so that typing "a e f" should match "safe". I know that by default in fzf typing "aef" without spaces will also match "safe" but I don't like this. I prefer typing spaces to adding ' for getting exact matches, see [the fzf syntax](https://github.com/junegunn/fzf?tab=readme-ov-file#search-syntax). Also my impression is that average users prefer my method. So if you refer to this I don't plan to add code for this at the moment.

Or do you ask for a typo resistant match so that "m**x** deck" also matches "m**y** deck", i.e. a matching method where characters missing from the deck/tag/card name don't rule out a match (real approximate matches)?

**Comment by ijgnd** [comment]
requirements for adding better matching:

- dependencies must be pure python 
- dependency should be very short or popular (so that it's in the debian repo)
- My background is not in IT. So I need info which algorithm to use how (similarity, distance, ...) ...

**Comment by dryBoneMarrow** [comment]
What I meant was a behavior like fuzzy finder, so "sfe" would match "safe", but "aef" does not match "safe". I proposed this functionality not knowing that I can use a space to separate multiple search terms. The current behavior is good enough and well suited for the plugin. So I'll close this issue, thank you for the response
