### ISSUE TITLE
incompatible with Advanced Browser

### ISSUE THREAD

**Issue by galantra** [ijgnd/anki__BetterSearch#4]
It doesn't work with [Advanced Browser](https://ankiweb.net/shared/info/874215009), does it? Or am I having other incompatibility issues…

**Comment by ijgnd** [comment]
I use my add-on with the Advanced Browser and so far I haven't noticed a problem. 

Update all add-ons and restart Anki? If your problem persists: Disable all add-ons apart from the advanced browser and my "Browser Search Box: Quick Insert Tag, Deck, Notetype": Does it work now?

If not: Can you describe exactly how to reproduce the problem?

If it works with just the two add-ons but not all your add-ons: Always keep my "advanced browser" and my "Browser Search Box: Quick Insert Tag, Deck, Notetype" enabled. Then disable half of the remaing add-ons and restart. Does it work now? If it works enable another half and try again. If it doesn't diable another half and try again, etc. Go back and forth a few times and you should quickly find the culprit. Can you tell me which combination doesn't work for you so that I can reproduce the problem and see if I can fix it

Thanks for your help.

**Comment by ijgnd** [comment]
I assume you no longer have a problem?
