### ISSUE TITLE
Feature suggestion: add options for "none", "filtered"

### ISSUE THREAD

**Issue by silentcicada1** [ijgnd/anki__BetterSearch#8]
I often search for cards that do not have tags within decks or want to move cards from one deck to another excluding filtered deck cards and this would be made much easier if when I typed "tag:" and you window popped up if there was an option for "none" and "filtered". I love your add on and I hope this feedback helps. Thank you

**Comment by ijgnd** [comment]
Thanks for the suggestion.

I just uploaded a new version to ankiweb that includes those. Could you try it out and let me know if you find bugs?

**Comment by silentcicada1** [comment]
It works awesome! Thank you for adding that so quickly.
I don't know if it was possible but if the none function was stickied to the top when "none" is searched. The reason I would suggest this is I can keep typing to get my other searches up (ex "nonenzyme") but that is not the case for "none".

https://drive.google.com/open?id=1PNPKolOZyy_ybs49nTX500HSsOPNB6Pm

**Comment by ijgnd** [comment]
Thanks for another great suggestion. I generalized it so that if your search string exactly matches a tag or deck this exact match is always put first. 

I just uploaded a new version to ankiweb that includes those. Could you try it out and let me know if it works and if you find bugs?

**Comment by silentcicada1** [comment]
I downloaded it and it is working great. This is a new add on for me and its really increased my daily efficiency, now even more than ever. Thank you!
I also wanted to ask if it would be possible to search for a tag that is not specifically selected. An example would be if I type "AK_Step1::*" it will show that tag and it's any subtags, but will not let you select to search "::*". I was wondering if it would be possible to type and if nothing matches exactly still enter the characters you've typed into the browser search instead of aborting.

https://drive.google.com/open?id=18M5FI47eREIILdpDzgMSEfaEXS5jGB48

**Comment by ijgnd** [comment]
that sounds interesting, too. Could you try the following version that's not yet on ankiweb and give some feedback: https://github.com/ijgnd/anki__browser_search__quick_insert_tag_deck_notetype/releases/download/0.04/anki__browser_search__quick_insert_tag_deck_notetype__2020-04-09.ankiaddon

**Comment by silentcicada1** [comment]
That is perfect! I really like how it retains all the same functionality of previous version your but with the added perk of using your text as desired. I especially love the append prepend functions. My only suggestion would be to make the append option "::*" to reduce typing since the colons are almost always needed. Thank you so much for all your hard work making this add on even better!

**Comment by silentcicada1** [comment]
or maybe make it customizable so people can key bind different frequently used functions...

**Comment by ijgnd** [comment]
as far as I see "mytag*" should match nearly the same as "mytag::*" so I don't think that changing this is that useful. The only difference is if the parent tag "mytag" is matched or not as fas as I see (did I miss something?) and I prefer it that way.

&nbsp;

I made another version . Could you just regularly use it and let me know if you run into problems in the next days?

Changes:
1. modifier keys fully user configurable
2. small errors removed
3. use json schema so that it works with Arthur's [Graphical form to change add-on configuration](https://ankiweb.net/shared/info/1014777615).

1 and 2 might have introduced new problems that's why I send it to you first.

you can download here: https://github.com/ijgnd/anki__browser_search__quick_insert_tag_deck_notetype/releases/download/0.05/anki__browser_search__quick_insert_tag_deck_notetype__2020-04-11.ankiaddon

Thanks for testing.

**Comment by silentcicada1** [comment]
These changes are amazing. I've really been able to customize my workflow. Thank you!
I've spent the last few hours trying out new feature in my normal workflow and so far I've only come up with one issue. When using the "card:" function the search function doesn't work as smoothly as in other windows (ex. "ste" doesn't find "step") and if there are multiple kinds of cards (ex. cloze1, cloze2) it will lump them all together as cloze. I recorded a video to demo what I'm referring to.
https://drive.google.com/open?id=1qOxsaNWjUpvGgReKDX3Zp058FtHf4VP7

Thanks again for all the hard work and I will continue to use this add on heavily and let you know if any other issues arise.

**Comment by ijgnd** [comment]
Thanks for the feedback.

If you don't use my add-on and search for `card:"Cloze"` you will get matches irrespective of the note type, e.g from the regular Cloze note type, but also from Cloze-AnKingMaster or "Enhanced Cloze 2.1".

If you just want cards from one note type you would have to search for e.g. `card:Cloze   note:"Cloze-AnKingMaster"`. 

With my add-on when you search for cards my addon also shows the name of the source note in brackets. I thought that this makes it easier but now I see that this is also confusing since you can infer from this that you will only get cards from this notetype. 

I changed the add-on so that when you enter `card:` you only see card names. There's also a new term: "cfn" for card-from-note: so when you type `cfn:` you'll see e.g.  `Cloze (Cloze-AnKingMaster)` (as you previously did for cards) and when you select this you get a search line `card:Cloze   note:"Cloze-AnKingMaster"`.

&nbsp;

You can search for:

- tag: * allowed in front and at back
- note (e.g. `note:*asi*`): * NOT allowed in front and at back in Anki 2.1.22 or lower BUT it works in 2.1.24 beta5
- card (e.g. `card:*loz*`): * NOT allowed in front and at back in Anki 2.1.22 or lower BUT it works in 2.1.24 beta5
- deck: * allowed in front and at back
- combined tag/deck: * allowed

So in 2.1.24 you can use `*` for all searches but not in 2.1.22. I added this to the add-on.

&nbsp;

These two changes (cfn and nostar for 2.1.22) are quite complicated. I made a new version. Could you test it? It likely contains errors because I actually should rewrite important parts of the add-on but I don't want to.

Here's the updated version: https://github.com/ijgnd/anki__browser_search__quick_insert_tag_deck_notetype/releases/download/0.05/anki__browser_search__quick_insert_tag_deck_notetype__2020-04-11_test.ankiaddon

@AnKingMed

**Comment by silentcicada1** [comment]
I am currently using 2.1.23 but I am having zero issues with the above changes. I really like the cfn: function. I'll keep you posted if I see any bugs, but I've put 4 hours of pretty heavy use and nothing yet! Thank you for all the changes, this add on is amazing!

**Comment by ijgnd** [comment]
That's very reassuring.

For your regular use in the coming days: If you haven't used shortcuts in the browser could you also sometimes use them and vice versa: If so far you relied on shortcuts could try typing in "tag:/deck:/..."

shortcuts and "typing tag:/deck/cfn:/..." use different functions so that if one works this does not mean that the other works. So both need testing. 

I will also just regularly use the add-on and if we don't find errors over the coming week I'll upload it to ankiweb.

Thanks for testing. That's very useful to me.

**Comment by silentcicada1** [comment]
I will continue using the add on extensively and will make sure to incorporate shortcuts and the typing. I'll make sure to let you know if I find any errors. Thank you!

**Comment by ijgnd** [comment]
I just published the add-on on ankiweb. You might get an update notification and a download though for you it will be the same add-on.

If you find another problem/bug or have another useful idea let me know in a new thread.

Thanks for your testing.
